apiVersion: v1
kind: Pod
metadata:
  name: nmap
spec:
  containers:
    - args:
        - while true; do sleep 30; done;
      command:
        - /bin/sh
        - '-c'
        - '--'
      image: quay.io/instrumentisto/nmap
      imagePullPolicy: Always
      name: nmap
