apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - args:
        - while true; do sleep 30; done;
      command:
        - /bin/sh
        - '-c'
        - '--'
      image: quay.io/wcaban/net-toolbox
      imagePullPolicy: Always
      name: toolbox


