apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  containers:
    - args:
        - while true; do sleep 30; done;
      command:
        - /bin/bash
        - '-c'
        - '--'
      image: praqma/network-multitool
      imagePullPolicy: Always
      name: toolbox


